---
title: Beginner HTML & CSS Sushi Cards
hero_image: images/banner.svg
description: Learn to make a website
theme: navy
duration: 1
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 前書き
  - 
    title: はじめに
  - 
    title: ウェブページをつくろう
  - 
    title: CSS（スタイルシート）を設定しよう
  - 
    title: リストをつくってみよう
  - 
    title: 画像を追加する
  - 
    title: さらにページをつくろう
  - 
    title: リンクをつくろう
  - 
    title: ウェブサイトをナビゲートしよう
  - 
    title: メニューバーのスタイリング
  - 
    title: マップとビデオの追加
  - 
    title: テーブルの追加
  - 
    title: プロジェクトのダウンロード
  - 
    title: What next?
