---
title: Leitfaden für mein Land 1.0
hero_image: images/banner.png
description: Lerne, wie du eine Website erstellst
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: Coderdojo, Projekte
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Erste Schritte
  - 
    title: Deine erste Webseite!
  - 
    title: Passe deine Seite an
  - 
    title: Bilder hinzufügen
  - 
    title: Hinzufügen einer Karte oder eines Videos
  - 
    title: Anlegen einer Liste
  - 
    title: Erstellen von Links
  - 
    title: Hinzufügen weiterer Seiten
  - 
    title: Auf deiner Website navigieren
  - 
    title: Eine Menüleiste erstellen
  - 
    title: Gestalten der Menüleiste
  - 
    title: Hinzufügen einer Tabelle
  - 
    title: Und noch mehr?
