---
title: Guía a mi país 1.0
hero_image: images/banner.png
description: Aprende a hacer un sitio web
theme: rojo #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: proyectos de CoderDojo
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Preparativos
  - 
    title: '¡Tu primera página web!'
  - 
    title: Controlando como se lucirá
  - 
    title: Agregando imagenes
  - 
    title: Agregando un mapa o un video
  - 
    title: Haciendo una lista
  - 
    title: Creando links
  - 
    title: Agregando más páginas
  - 
    title: Navengando tu sitio web
  - 
    title: Haciendo un menú de barra
  - 
    title: Definiendo el estilo del menú de barra
  - 
    title: Agregando una tabla
  - 
    title: '¿Qué sigue?'
