---
title: Przewodnik po moim kraju 1.0
hero_image: images/banner.png
description: Dowiedz się, jak stworzyć stronę internetową
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projekty, polish, polski
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Przygotowanie do pracy
  - 
    title: Twoja pierwsza strona internetowa!
  - 
    title: Kontrolowanie wyglądu
  - 
    title: Dodawanie zdjęć
  - 
    title: Dodawanie mapy lub wideo
  - 
    title: Utwórz listę
  - 
    title: Tworzenie linków
  - 
    title: Dodawanie kolejnych stron
  - 
    title: Poruszanie się po twojej stronie internetowej
  - 
    title: Tworzenie paska menu
  - 
    title: Stylizacja paska menu
  - 
    title: Dodawanie tabeli
  - 
    title: Co dalej?
