---
title: Carte Sushi HTML / CSS per principianti
hero_image: images / banner.png
description: Impara a creare un sito web
theme: rosso
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, progetti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Preparazione
  - 
    title: La tua prima pagina web!
  - 
    title: Controllare come appare
  - 
    title: Aggiungere foto
  - 
    title: Aggiungere una mappa o un video
  - 
    title: Creare una lista
  - 
    title: Creare collegamenti
  - 
    title: Aggiungere più pagine
  - 
    title: Navigare nel tuo sito web
  - 
    title: Creare una barra dei menu
  - 
    title: Dare uno stile alla la barra dei menu
  - 
    title: Aggiungere una tabella
